### ISSUE TITLE
Non-OSI license

### ISSUE THREAD

**Issue by mvdh7** [ZijieZhaoMMHW/m_mhw1.0#1]
[For JOSS review](https://github.com/openjournals/joss-reviews/issues/1124)

The license file simply states a name and a year, and does not appear to refer to any from the [OSI approved list](https://opensource.org/licenses/alphabetical) as required by JOSS.

**Comment by ZijieZhaoMMHW** [comment]
Done.

**Comment by mvdh7** [comment]
It appears that you have either decided to credit me as the author of your software, or you have copied and pasted a license from one of my repositories. This is an odd decision as none of my code is published with JOSS. I suggest you update the license so that it applies to your own software and check it matches the OSI approved list as required by JOSS.

**Comment by ZijieZhaoMMHW** [comment]
Sorry, I misunderstand this point. I would fix this issue.

**Comment by ZijieZhaoMMHW** [comment]
Please see https://github.com/ZijieZhaoMMHW/m_mhw1.0/blob/master/docs/LICENCE.txt.

Now I use the GNU GENERAL PUBLIC LICENSE Version 3.

**Comment by mvdh7** [comment]
There are still lines in the license file that need to be updated with your details
e.g. line 656 `<program>  Copyright (C) <year>  <name of author>`
And others! :)

**Comment by ZijieZhaoMMHW** [comment]
Hi. I have modified the license. 

see Line 656 `<m_mhw>  Copyright (C) <2019>  <Zijie Zhao>`
see Line 635 `<A MATLAB toolbox to detect and analyze marine heatwaves>
    Copyright (C) <2019>  <Zijie Zhao>`
