### ISSUE TITLE
issue in the mean_and_trend function

### ISSUE THREAD

**Issue by MazenBayoumy** [ZijieZhaoMMHW/m_mhw1.0#21]
I have found two issues in the new code
1_ In the mean_and_trend function, the 1982 should be changed to data_here as not all people used the data from 1982. 
2- the output of MHW days is not the same as in the old version. 
Thanks

**Comment by ZijieZhaoMMHW** [comment]
> I have found two issues in the new code 1_ In the mean_and_trend function, the 1982 should be changed to data_here as not all people used the data from 1982. 2- the output of MHW days is not the same as in the old version. Thanks

Thanks for identifying the issue. I will start to work on fixing it tomorrow.

Cheers,
Zijie
