### ISSUE TITLE
Function inputs documentation

### ISSUE THREAD

**Issue by mvdh7** [ZijieZhaoMMHW/m_mhw1.0#3]
[For JOSS review](https://github.com/openjournals/joss-reviews/issues/1124)

Documentation on the functions’ API in the readme includes a description of their outputs but nothing on inputs. Inputs are described in code comments within the functions themselves, but it would be helpful to have this info in the readme too.

**Comment by ZijieZhaoMMHW** [comment]
Done.

**Comment by mvdh7** [comment]
Thank you.

I should have noticed this previously but clearly did not spot it. Is there also documentation for the `event_line()` and `mean_and_trend()` function input/outputs too? Are these intended for use by the end user?

**Comment by ZijieZhaoMMHW** [comment]
Sincere thanks for suggestion. But considering adding description of them into readme.md would make it too long and they are well documented in MATLAB `help` text, so I just mention this point in readme.md. See https://github.com/ZijieZhaoMMHW/m_mhw1.0/blob/master/README.md

**Comment by mvdh7** [comment]
Okay, I think that solution is okay
