### ISSUE TITLE
Results inconsistencies with other implementations

### ISSUE THREAD

**Issue by mvdh7** [ZijieZhaoMMHW/m_mhw1.0#6]
[For JOSS review](https://github.com/openjournals/joss-reviews/issues/1124)

The noted differences in results between the different implementations (MATLAB, Python, R) are worrisome. It's said that this is caused by differences in how the different languages evaluate percentile thresholds, but surely the code could be adapted to enforce consistent calculations? If not, can you demonstrate that this is the **only** difference between the implementations, and thus prove that no other discrepancies are hiding behind it?

**Comment by ZijieZhaoMMHW** [comment]
Please see https://github.com/ZijieZhaoMMHW/m_mhw1.0/blob/master/testing/compare_M_R.md
